#!/bin/env bash
exec 2>>/dev/null

pw3image()
{
image="$1"

read -r TOP LEFT LINES COLS< <(tmux display -t $my_pane -p '#{pane_top} #{pane_left} #{pane_height} #{pane_width}')
((img_y=TOP*FONT_H, img_x=LEFT*FONT_W, pane_w=COLS*FONT_W, pane_h=(LINES-1)*FONT_H))

[[ -e "$image_bg" && "$image" == FTL_ERASE_BG ]] && { echo -e "0;1;$img_x;$img_y;$pane_w;$pane_h;;;;;$image_bg\n4;\n3;" >&7 ; return ; }

# for images that take too long to display or have changed, kill the displaying process and display new image
[[ "$image" == FTL_RESTART_W3M ]] && { kill $w3iproc &>/dev/null ; { <&7 /usr/lib/w3m/w3mimgdisplay &> /dev/null & } ; w3iproc=$! ; }

[[ -e "$image" ]] || return ; 

read -r img_w img_h < <(identify -format '%w %h' "$image") ;
((img_w==0 || img_h==0)) && { img_h=1 ; img_w=1 ; } ; rw=0 ; rh=0

((!scale || img_w > pane_w || img_h > pane_h)) && \
	{ { read img_sw ; read img_sh ; } < <(bc <<<"scale=2 ; r=rw=$pane_w/$img_w ; rh=$pane_h/$img_h ; if(rh<rw) r=rh ; if(r>1) r=1 ; scale=0 ; $img_w*r/1; $img_h*r/1") ; } || \
	{ img_sw=$img_w ; img_sh=$img_h ; }

echo -e "0;1;$img_x;$img_y;$img_sw;$img_sh;;;;;$image\n4;\n3;" >&7 ;
[[ -e "$image_bg" ]] && (( CLEAN_IMAGE )) &&
	{
	((img_sw < pane_w)) && echo -e "0;1;$((img_x+img_sw));$img_y;$((pane_w - img_sw));$img_sh;;;;;$image_bg\n4;\n3;" >&7
	((img_sh < pane_h)) && echo -e "0;1;$img_x;$((img_y+img_sh));$pane_w;$((pane_h - img_sh));;;;;$image_bg\n4;\n3;" >&7
	}

# echo CLEAN: $CLEAN_IMAGE, FONT: $FONT_W \* $FONT_H
# echo TOP: $TOP, LEFT: $LEFT, LINES: $LINES, COLS: $COLS, LINES: $LINES, COLS: $COLS, RIGHT: $((img_x + pane_w)), pane_w: $pane_w, pane_h: $pane_h
# echo -e "img_x: $img_x,img_y: $img_y, img_w: $img_w, img_h: $img_h, $img_y, img_sw: $img_sw, img_sh: $img_sh"
# ((img_sw < pane_w)) && echo redraw right $((img_x+img_sw)) $img_y $((pane_w - img_sw)) $img_sh
# ((img_sh < pane_h)) && echo redraw bottom $img_x $((img_y+img_sh)) $pane_w $((pane_h - img_sh))
}

pid_2_pane(){ while read -s pi pp ; do [[ $1 == $pp ]] || [[ $(ps -o pid --no-headers --ppid $pp | rg $$) ]] && echo $pi && break ; done < <(tmux lsp -F '#{pane_id} #{pane_pid}') ; }
my_pane=$(pid_2_pane $$)

# args: location for pipe, image, clear around image, font width, font height
stty -echo
tput civis

#todo: scale
CLEAN_IMAGE=${3:-1}
FONT_W=${4:-10}
FONT_H=${5:-19}

image_bg="$HOME/.config/ftl/image_bg.png"

[[ -e $1/W3M_PIPE ]] || mkfifo $1/W3M_PIPE ; eval "exec 7<>$1/W3M_PIPE"
{ <&7 /usr/lib/w3m/w3mimgdisplay &> /dev/null & } ; w3iproc=$!

[[ -e "$2" ]] && pw3image "$2"
while read -r n ; do pw3image "$n" ; done

