#!/bin/env bash
stty -echo
tput civis

pw3image()
{
image="$1" ; read -r img_w img_h < <(identify -format '%w %h' "$image") ; image_bg="$HOME/.config/ftl/image_bg.png"
((img_w==0 || img_h==0)) && { img_h=1 ; img_w=1 ; } ; rw=0 ; rh=0

FONT_W=10 ; FONT_H=19
read -r TOP LEFT LINES COLS< <(tmux display -t $my_pane -p '#{pane_top} #{pane_left} #{pane_height} #{pane_width}')
((img_y=TOP*FONT_H, img_x=LEFT*FONT_W, pane_w=COLS*FONT_W, pane_h=(LINES-1)*FONT_H))

((img_w > pane_w || img_h > pane_h)) && \
	{ { read img_sw ; read img_sh ; } < <(bc <<<"scale=2 ; r=rw=$pane_w/$img_w ; rh=$pane_h/$img_h ; if(rh<rw) r=rh ; if(r>1) r=1 ; scale=0 ; $img_w*r/1; $img_h*r/1") ; } || \
	{ img_sw=$img_w ; img_sh=$img_h ; }

                       echo -e "0;1;$img_x;$img_y;$img_sw;$img_sh;;;;;$image\n4;\n3;" >&7 ;
((img_sw < pane_w)) && echo -e "0;1;$((img_x+img_sw));$img_y;$((pane_w - img_sw));$img_sh;;;;;$image_bg\n4;\n3;" >&7
((img_sh < pane_h)) && echo -e "0;1;$img_x;$((img_y+img_sh));$pane_w;$((pane_h - img_sh));;;;;$image_bg\n4;\n3;" >&7

#echo TOP: $TOP, LEFT: $LEFT, LINES: $LINES, COLS: $COLS, LINES: $LINES, COLS: $COLS, RIGHT: $((img_x + pane_w)), pane_w: $pane_w, pane_h: $pane_h
#echo -e "img_x: $img_x,img_y: $img_y, img_w: $img_w, img_h: $img_h, $img_y, img_sw: $img_sw, img_sh: $img_sh" ,
}

pid_2_pane(){ while read -s pi pp ; do [[ $1 == $pp ]] || [[ $(ps -o pid --no-headers --ppid $pp | rg $$) ]] && echo $pi && break ; done < <(tmux lsp -F '#{pane_id} #{pane_pid}') ; }
my_pane=$(pid_2_pane $$)

PIPE=$(mktemp -u) && mkfifo $PIPE && eval "exec 7<>$PIPE" && rm $PIPE
{ <&7 /usr/lib/w3m/w3mimgdisplay &> /dev/null & } ; w3iproc=$!

[[ -e "$1" ]] && pw3image "$1"
while read -r n ; do [[ -e "$n" ]] && pw3image "$n"  ; done
