#!/bin/bash
exec 2>> "$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.jpg"

[[ "$4" = ONE ]] && { echo "$t" ; exit ; }

[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	unrar p -ierr -inull -c- "$1" "$(rar lb "$1" \*.jpg \*.png | perl -ne '! /\d\D\..*$/ and print' | sort | head -n1)" > "$2/$f.large.jpg"
	vipsthumbnail --size 600x "$2/$f.large.jpg" -o "$t"
	rm "$2/$f.large.jpg" 2>&-
	}

echo "$t"
