#!/bin/bash
exec 2>> "$2/generators_log"

f=$(basename "$1")

[[ FORCE == "$3" || ! -f "$2/$f.jpg" ]] &&
	{
	unzip -p "$1"  "$(zipinfo -2  "$1" | perl -ne '! /\d\D\..*$/ and print' | sort | head -n1)" > "$2/$f.large.jpg" && vipsthumbnail --size 600x "$2/$f.large.jpg" -o "$2/$f.jpg" \
		|| cbconvert thumbnail "$1" --outfile "$2/$f.jpg" &>/dev/null

	rm "$2/$f.large.jpg" 2>&-
	}
