#!/bin/bash
exec 2>> "$2/generators_log"

n=$(basename "$1")

[[ FORCE == "$3" || ! -f "$2/$n.jpg" ]] &&
	{
	unzip -p "$1"  "$(zipinfo -2  "$1" | perl -ne '! /\d\D\..*$/ and print' | sort | head -n1)" > "$2/$n.large.jpg" && vipsthumbnail --size 600x "$2/$n.large.jpg" -o "$2/$n.jpg" \
		|| cbconvert thumbnail "$1" --outfile "$2/$n.jpg" &>/dev/null

	rm "$2/$n.large.jpg" 2>&-
	}
