#!/bin/bash
exec 2>> "$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"

extmode=${3:-0}
p="$2/$f.$extmode.txt"

[[ FORCE == "$3" || ! -f "$p" ]] &&
	{
	mutool convert -o "$p" "$1" $( (($extmode)) || echo 1-3) 2>/dev/null
	}

