#!/bin/bash
exec 2>> "$2/generators_log"

extmode=${3:-0}

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.$extmode.txt"

[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	mutool convert -o "$t" "$1" 2>/dev/null
	}

echo "$t"
