#!/bin/bash
exec 2>> "$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"

extmode=${3:-0}
p="$2/$f.$extmode.txt"

printf "%s\n" "$@" >&2
echo generating "$p" >&2

[[ FORCE == "$4" || ! -f "$p" ]] &&
	{
	mutool convert -o "$p" "$1" 2>/dev/null
	}

