#!/bin/bash

# <"$1/generator_time" read -r start 2>&-
# end=$(date +%s%N)

# { (( start == 0 )) || (( (end - start) < 50000000 )) ; } && exit 0

# echo 0 >"$1/generator_time"
# { echo -n "s: " ; date +%c ; } >>"$1/generator_time_all"

for g in $(fd . $FTL_CFG/etc/generators/ -t f -d 1 -E generator -E generator_one)
	do 
		ext=$(basename $g)
		mkdir -p "$1/$ext"
		fd "\.$ext$" -t f -d 1 --exec "$g" "$PWD/"{/} "$1/$ext"
	done

# date +%s%N >"$1/generator_time"
# { echo -n "e: " ; date +%c ; } >>"$1/generator_time_all"

