#!/bin/bash

# <"$1/generator_time" read -r start 2>&-
# end=$(date +%s%N)

# { (( start == 0 )) || (( (end - start) < 50000000 )) ; } && exit 0

# echo 0 >"$1/generator_time"
# { echo -n "s: " ; date +%c ; } >>"$1/generator_time_all"

[[ "$(shopt -s nullglob dotglob; echo *)" ]] || exit 0

ext_regexp='å'

for g in $FTL_CFG/etc/generators/*
	do
		ext=$(basename "$g")
		[[ "$ext" == generator || "$ext" == generator_one || "$ext" == montage || "$ext" == 'svg_to_pdf' ]] && continue
		
		ext_regexp+="|$ext"
	done

# dir_hash=$(md5sum <<<"$PWD" | cut -d' ' -f1)

find * -maxdepth 0 -type f | grep -P "($ext_regexp)$" | parallel --plus "$FTL_CFG/etc/generators/{/.*\\./}" "\"$PWD/{/}\"" "\"$1/{/.*\\./}\"" &>/dev/null

# date +%s%N >"$1/generator_time"
# { echo -n "e: " ; date +%c ; } >>"$1/generator_time_all"

# vim: set filetype=bash :
