#!/bin/bash
mkdir -p "$2"
exec 2>> "$2/generators_log"

f="$(head -c 1024 "$1" | md5sum | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.et"

# source $ftl_info_file # to get FTL_FS needed by pdh
# export FTL_FS="$FTL_FS"

[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	exiftool "$1" | piper '^.*?:' blue >"$t"
	# pdh mp3 cache "$t" $(stat -c %Y "$t" && echo " found")
	}

echo "$t"
