#!/bin/bash
exec 2>>"$2/generators_log"

f=$(basename "$1")

[[ FORCE == "$3" || ! -f "$2/$f.jpg" ]] && 
	{
	ffmpegthumbnailer -i "$1" -o "$2/$f.jpg" -s 1024
	exiftool "$1" | piper '^.*?:' blue >"$2/$f.et"
	}

