#!/bin/bash
exec 2>> "$2/generators_log"

extmode=${3:-0}

f=$(basename "$1")
p="$2/$f$extmode.txt"

[[ FORCE == "$3" || ! -f "$p" ]] &&
	{
	mutool draw -o "$p" "$1" $( (($extmode)) || echo 1-3 ) 2>/dev/null
	}

