#!/bin/bash
mkdir -p "$2"
exec 2>> "$2/generators_log"

extmode=${3:-0}

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.$extmode.txt"

# source $ftl_info_file # to get FTL_FS needed by pdh
# # export FTL_FS="$FTL_FS"


[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	mutool draw -o "$t" "$1" $( (($extmode)) || echo 1-3 ) 2>/dev/null
	}

echo "$t"

