#!/bin/bash
mkdir -p "$2"
exec 2>> "$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.png"

[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	echo "import(\"$1\");" > "$2/import.scad"
	openscad -o "$t" --imgsize=500,500 "$2/import.scad"
	rm "$2/import.scad"
	}

echo "$t"

