#!/bin/bash
exec 2>> "$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"

[[ FORCE == "$4" || ! -f "$2/$f.jpg" ]] &&
	{
	rsvg-convert --background-color=white "$1" > "$2/$f.jpg"
	}


