#!/bin/bash
exec 2>> "$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.pdf"

[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	rsvg-convert -f pdf -o "$t" "$1" 
	}

echo "$t"
