#!/bin/bash
exec 2>>"$2/generators_log"

f="$(md5sum <<<"$1" | cut -d' ' -f1)_$(basename "$1")"
t="$2/$f.jpg"

[[ FORCE == "$4" || "$t" -ot "$1" ]] &&
	{
	ffmpegthumbnailer -i "$1" -o "$t" -s 1024 || rm "$t.jpg"
	exiftool "$1" | piper '^.*?:' blue >"$2/$f.et"
	}

echo "$t"
