#!/bin/bash
exec 2>>"$2/generators_log"

n=$(basename "$1")

[[ FORCE == "$3" || ! -f "$2/$n.jpg" ]] && 
	{
	ffmpegthumbnailer -i "$1" -o "$2/$n.jpg" -s 1024 || rm "$2/$n.jpg"
	exiftool "$1" | piper '^.*?:' blue >"$2/$n.et"
	}

