#!/bin/bash
exec 2>> "$2/generators_log"

[[ -f "$2/$1.jpg" ]] || 
	{
	unzip -p "$1"  "$(zipinfo -2  "$1" | perl -ne '! /\d\D\..*$/ and print' | sort | head -n1)" > "$2/$1.large.jpg" & vipsthumbnail --size 600x "$2/$1.large.jpg" -o "$2/$1.jpg" \
		|| cbconvert thumbnail "$1" --outfile "$2/$1.jpg" &>/dev/null
	}
