#!/bin/bash
exec 2>>"$2/generators_log"

[[ -f "$2/$1.jpg" ]] || 
	{
	ffmpegthumbnailer -i "$1" -o "$2/$1.jpg" -s 1024
	
	t="$2/et_$(head -c50000 "$1" | md5sum | cut -f1 -d' ')"
	[[ -f "$t" ]] || 
		{
		exiftool "$1" | piper '^.*?:' blue >$t  
		}
	}

