#!/bin/bash

fs=/tmp/$USER
mkdir -p $fs

source $ftl_state_info_file_path # to get serialized information from * ftl *

{ 
echo ftl_state_info_file_path: $ftl_state_info_file_path
echo FTL_PID: $FTL_PID
echo FTL_CWD: $FTL_CWD
echo current entry: $n
echo Selection: ;        printf "\t%s\n" "${selection[@]}"
echo Arguments: ;        printf "\t%s\n" "$@"
} >$fs/02_example_info

tmux popup cat $fs/02_example_info

# vim: set filetype=bash :

